version: '3'
services:
  pyspark-notebook:
    image: "jupyter/all-spark-notebook"
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work/data
